on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: ${{ github.base_ref }}
      gh-env:
        type: string
        required: true
    secrets:
      PAT:
        required: true

jobs:
  pre:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh-env }}
    steps:
      - name: pre work
        run: |
          echo "workflow ${{ vars.ENV }}."
          echo "tag: ${{ secrets.TAG }}"

  work:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs: pre
    steps:
      - name: dispatch workflow
        uses: actions/github-script@v6
        with:
          debug: true
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'dispatch-test',
              workflow_id: 'work.yaml',
              ref: '${{ inputs.branch }}',
              inputs: {
                'no-cache': true,
              }
            })
