on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  work:
    uses: ./.github/workflows/reusable-work.yaml
    with:
      env: work2
  post-work:
    needs: work
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: |
          echo "post work."
